## 문제1. Hello, Python! 을 출력한다.

In [ ]:
print('Hello, Python!')

## 문제2. 반지름 r = 10인 원의 넓이를 구하시오.
input() 함수를 이용해 반지름 r을 입력받아 계산해서 출력할 것. (pi = 3.14)

In [1]:
num = int(input('반지름 길이 입력 :'))
pi = 3.14
print(pi * (num**2))

314.0

## 문제3. 변수 a와 변수 b의 값을 서로 바꾸시오.
아래 ... 부분을 채워서 결과를 낼 것.
a = 'AAA' 
b = 'BBB'
...
print('a=', a, 'b=', b)

In [4]:
a = 'AAA'
b = 'BBB'
c = a
a = b
b = c
print('a=', a,'b=', b)

a= BBB b= AAA

## 문제4. 리스트 생성과 조작
문제 3-1) 'apple', 'banana', 'cat', 'dog' 로 구성된 리스트 list1를 만들고 출력하시오.

문제 3-2) 위 리스트에 'elephant'를 추가한 뒤 출력하시오.

문제 3-3) 리스트에 있는 원소의 갯수를 구해서 출력하시오.

문제 3-4) 리스트 맨 마지막의 원소를 출력하시오.

In [5]:
# 문제3-1)
list1 = ['apple', 'banana', 'cat', 'dog' ]
print(list1)
# 문제3-2)
list1.append('elephant')
print(list1)
# 문제3-3)
print(len(list1)) 
# 문제3-4)
print(list1[-1])

['apple', 'banana', 'cat', 'dog']
['apple', 'banana', 'cat', 'dog', 'elephant']
5
elephant

## 문제5. while문의 활용
factorial값 N! = 1 * 2 * 3 * ... * (N-1) * N 로 정의된다.
N! 가 최초로 1000을 초과하게 되는 N과 N!값을 구해서 출력하시오.

In [7]:
N = 1
num = 1
while True :
    if N > 1000 :
        break
    else :
        num *= N
        N += 1
print(N, num)

1001 402387260077093773543702433923003985719374864210714632543799910429938512398629020592044208486969404800479988610197196058631666872994808558901323829669944590997424504087073759918823627727188732519779505950995276120874975462497043601418278094646496291056393887437886487337119181045825783647849977012476632889835955735432513185323958463075557409114262417474349347553428646576611667797396668820291207379143853719588249808126867838374559731746136085379534524221586593201928090878297308431392844403281231558611036976801357304216168747609675871348312025478589320767169132448426236131412508780208000261683151027341827977704784635868170164365024153691398281264810213092761244896359928705114964975419909342221566832572080821333186116811553615836546984046708975602900950537616475847728421889679646244945160765353408198901385442487984959953319101723355556602139450399736280750137837615307127761926849034352625200015888535147331611702103968175921510907788019393178114194545257223865541461062892187960223838971476088506276862967146674697562911234082439208160153780889893964518263243671616762179168909779911903754031274622289988005195444414282012187361745992642956581746628302955570299024324153181617210465832036786906117260158783520751516284225540265170483304226143974286933061690897968482590125458327168226458066526769958652682272807075781391858178889652208164348344825993266043367660176999612831860788386150279465955131156552036093988180612138558600301435694527224206344631797460594682573103790084024432438465657245014402821885252470935190620929023136493273497565513958720559654228749774011413346962715422845862377387538230483865688976461927383814900140767310446640259899490222221765904339901886018566526485061799702356193897017860040811889729918311021171229845901641921068884387121855646124960798722908519296819372388642614839657382291123125024186649353143970137428531926649875337218940694281434118520158014123344828015051399694290153483077644569099073152433278288269864602789864321139083506217095002597389863554277196742822248757586765752344220207573630569498825087968928162753848863396909959826280956121450994871701244516461260379029309120889086942028510640182154399457156805941872748998094254742173582401063677404595741785160829230135358081840096996372524230560855903700624271243416909004153690105933983835777939410970027753472000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

## 문제6. for 문의 활용
1~30 까지의 숫자 중 2, 3, 5의 배수만 빼고 출력하시오.

In [10]:
for l in range(1, 31) :
    if l % 2 != 0 :
        if l % 3 != 0 :
            if l % 5 != 0 :
                print(l)

1
7
11
13
17
19
23
29

## 문제7. 주민등록번호를 입력받아, 성별과 출생년도를 추출하시오.
input() 함수를 이용해 주민등록번호를 XXXXXX-XXXXXXX 형식으로 입력받을 것. 

문제 6-1) 주민등록번호에서 성별정보를 추출해 변수 gender = '남성' 또는 '여성'으로 저장하고, 출력하시오.

문제 6-2) 주민등록번호에서 출생년도를 계산해 변수 year 에 네자리수 값(OOOO)으로 저장하시오. (출생년도는 1901년~2022년 사이이다)

테스트 케이스로 다음을 사용해볼 것: 991111-1111111, 991111-2222222, 111111-3333333, 111111-444444

In [17]:
id_num = input("주민등록번호를 입력하세요 (OOOOOO-XXXXXXX):")
# 문제 6-1
gender = 0
if id_num[7] == '1' or id_num[7] == '3' :
    gender = '남성'
else :
    gender = '여성'
print(gender)
# 문제 6-2
year = id_num[:2]
if int(year) < 23 :
    if id_num[8] == '1' :
        print('19' + year)
    else :
        print('20' + year)
else :
    print(19 + year)

여성
2003

## 문제8. 2~1000 사이의 소수 찾기
2~1000 범위에서 소수의 목록(또는 갯수)을 구하시오.

In [23]:
import math
list2 = []
for i in range(2, 1001) :
    num = 0
    for j in range(2, int(math.sqrt(i))) :
        if i % j == 0 :
            num = 1
            
    if num == 0 :
        list2.append(i)
print(list2)

[2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 15, 17, 19, 23, 25, 29, 31, 35, 37, 41, 43, 47, 49, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 121, 127, 131, 137, 139, 143, 149, 151, 157, 163, 167, 169, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 289, 293, 307, 311, 313, 317, 323, 331, 337, 347, 349, 353, 359, 361, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 529, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 841, 853, 857, 859, 863, 877, 881, 883, 887, 899, 907, 911, 919, 929, 937, 941, 947, 953, 961, 967, 971, 977, 983, 991, 997]