In [1]:
import pandas as pd

In [ ]:
# 데이터 불러오기
temper = pd.read_csv('연안정지 관측자료.csv')
temper

,해역,연안정점,관측일시,수온,수온 QC Flag,기온,기온 QC,운량,천기
0,남해,가덕도(20201),20130101,10.2,1,5.0,1,21%-30%,개임(운량:3-7)
1,남해,가덕도(20201),20130102,NaN,2,-3.5,2,41%-50%,개임(운량:3-7)
2,남해,가덕도(20201),20130103,NaN,2,-5.5,2,11%-20%,쾌청(운량:0-2)
3,남해,가덕도(20201),20130104,9.8,2,-1.8,2,11%-20%,쾌청(운량:0-2)
4,남해,가덕도(20201),20130105,9.9,1,0.5,1,11%-20%,쾌청(운량:0-2)
...,...,...,...,...,...,...,...,...,...
37998,남해,화양(22001),20221214,11.4,2,-0.3,2,11%-20%,쾌청(운량:0-2)
37999,남해,화양(22001),20221215,10.5,2,1.0,2,Zero,쾌청(운량:0-2)
38000,남해,화양(22001),20221216,10.4,2,3.4,2,51%-60%,개임(운량:3-7)
38001,남해,화양(22001),20221229,9.7,2,2.7,2,Zero,쾌청(운량:0-2)
38002,남해,화양(22001),20221230,9.9,2,3.8,2,11%-20%,쾌청(운량:0-2)

In [7]:
# 부산 키워드 있는 데이터만 뽑고 해파리 데이터와의 값 통일을 위하여 지역 칼럼 추가
temper = temper[temper['연안정점'].str.contains("부산")]
temper['지역'] = '부산'

In [ ]:
# 년도와 월별 데이터를 출력
temper['year'] = temper['관측일시'].astype(str).str[:4]
temper['month'] = temper['관측일시'].astype(str).str[4:6]

/var/folders/s0/flnd6hf15vs62n5vkdlhyg_m0000gn/T/ipykernel_52955/2134506136.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temper['year'] = temper['관측일시'].astype(str).str[:4]
/var/folders/s0/flnd6hf15vs62n5vkdlhyg_m0000gn/T/ipykernel_52955/2134506136.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temper['month'] = temper['관측일시'].astype(str).str[4:6]

In [8]:
# 수온 칼럼을 기준으로 Null 값이 들어있는 행 제거
temper.dropna(subset=['수온'], inplace=True)

In [ ]:
temper.to_csv('부산 수온.csv')

,해역,연안정점,관측일시,수온,수온 QC Flag,기온,기온 QC,운량,천기,지역,year,month
11542,남해,부산(20103),20130101,13.5,2,1.5,2,11%-20%,쾌청(운량:0-2),부산,2013,01
11543,남해,부산(20103),20130102,13.3,2,1.2,2,21%-30%,개임(운량:3-7),부산,2013,01
11544,남해,부산(20103),20130103,12.9,2,-6.3,2,11%-20%,쾌청(운량:0-2),부산,2013,01
11545,남해,부산(20103),20130104,12.9,2,-5.0,2,1%-10%,쾌청(운량:0-2),부산,2013,01
11546,남해,부산(20103),20130105,12.4,2,-4.0,2,1%-10%,쾌청(운량:0-2),부산,2013,01
...,...,...,...,...,...,...,...,...,...,...,...,...
12979,남해,부산(20103),20161218,14.6,2,6.8,2,Zero,NaN,부산,2016,12
12980,남해,부산(20103),20161219,15.0,2,9.2,2,Zero,NaN,부산,2016,12
12981,남해,부산(20103),20161220,15.0,2,11.6,2,Zero,NaN,부산,2016,12
12982,남해,부산(20103),20161221,15.5,2,12.3,2,Zero,NaN,부산,2016,12
12987,남해,부산(20103),20161226,15.3,2,9.8,2,Zero,NaN,부산,2016,12